---
title: "Fitbit"
author: "Team39"
date: '2022-10-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(corrplot)


FitbitAct <- read.csv(file.choose()) #use dailyActivity_merged.csv
FitbitSleep <- read.csv(file.choose()) #use sleepDay_merged.csv
FitbitSleep$SleepDay <- strptime(FitbitSleep$SleepDay, format = "%m/%d/%Y %I:%M:%S %p")
FitbitAct$ActivityDate <- strptime(FitbitAct$ActivityDate, format = "%m/%d/%Y")

Fitbit <- FitbitAct %>%
      inner_join(FitbitSleep, by = c("Id", "ActivityDate" = "SleepDay"))
#Use Fitbit date frame for further analysis

Fitbit <- Fitbit %>%
      mutate(TimeInBedNotSleeping = TotalTimeInBed - TotalMinutesAsleep)
```

#EDA
```{r}
length(unique(Fitbit$Id))
#The problem here is that we only have 24 unique users who have both the activity record and sleep record

ggplot(Fitbit, aes(x = Calories, y = TotalMinutesAsleep)) +
      geom_point() +
      facet_wrap(~Id)

ggplot(Fitbit, aes(x = Calories, y = TimeInBedNotSleeping)) +
      geom_point() +
      facet_wrap(~Id)

ggplot(Fitbit, aes(x = Calories)) +
      geom_density() +
      facet_wrap(~Id)

#correlations between numerica variables
numV <- which(sapply(Fitbit, is.numeric)) #saving the indices of numeric columns
corNumV <- cor(Fitbit[,numV],use="pairwise.complete.obs")
corNumV_sort <- as.matrix(sort(corNumV[,'TimeInBedNotSleeping'],decreasing = TRUE)) #sort based on the correlation of variable with SalePrice
CorNumV_high <- names(which(apply(corNumV_sort, 1, function(x) abs(x)>0.1))) #the apply function cannot be applied to a vector, so transform corNum_sort to matrix is necessary
corNumV1 <- corNumV[CorNumV_high,CorNumV_high]
corrplot.mixed(corNumV1, tl.col="black", tl.pos = "lt", number.cex = 0.7)


medianCal <- median(Fitbit$Calories)
ggplot(Fitbit, aes(x = Calories)) +
      geom_density() +
      geom_vline(xintercept = medianCal, size = 1, color = "red") +
      geom_text(aes(x = medianCal + 500, label = paste0("median\n", medianCal), y = 5e-04))

ggplot(Fitbit, aes(x = SedentaryMinutes, y = TotalMinutesAsleep)) +
      geom_point() +
      stat_smooth(method = "lm",formula = y ~ x, geom = "smooth")
```

```{r}
weirdrows <- which((Fitbit$SedentaryMinutes + Fitbit$TotalMinutesAsleep) > 24*60)
Fitbit <- Fitbit[-weirdrows,]
      
```

#Simple Linear model
            Treatment: SedentaryMinutes
            Control: Everthing else
            Target: TotalMinutesAsleep
#VIF：      Test multicollinearity
#Heteroblabla: plot residuals (bptest)
#OVB:
            Potential IV: 
            1)temperature of the room(gender); 
            2)price of the chair(age)
#DiD:


```{r}

ggplot(Fitbit, aes(x = TotalMinutesAsleep)) +
      geom_histogram()
```



